---
title: "Teaching"
---

For the past [10 years](files/cv.pdf), I have taught ecology and evolution courses in Brazil and the United States as a teaching assistant in multiple different courses related to Ecology and Evolutionary biology. I also presented a few workshops in different places that generated a fair amount of education material. Here I am slowly compiling some of the resources I've produced:

# Software and tutorials

## Evolved: open software for teaching evolutionary biology

[`evolved`](https://mjanuario.github.io/evolved/), an open-source R package for undergraduate and graduate teaching in evolutionary biology. It provides tutorials with clear learning objectives focused on data visualization, hypothesis testing, and simulation-based reasoning using real datasets, enabling students to explore both microevolutionary processes (e.g., selection and drift) and macroevolutionary patterns from molecular and fossil data. The software stable version is available on [CRAN](https://cloud.r-project.org/web/packages/evolved/index.html), the development version can be found in my [github](https://github.com/mjanuario/evolved/). It was published in the [Journal of Open Source Education](https://doi.org/10.21105/jose.00300) and received the [2026 T. H. Huxley Award for education resources from the Society for the Study of Evolution](https://www.evolutionsociety.org/news/display/2026/4/27/2026-t-h-huxley-award-mr-matheus-januario-lopes-de-sousa/).

Please reach out if you would like to use evolved. Some of the investigation prompts are intentionally not publicly available online, but I’m happy to share this material with any human interested in using the software to teach evolutionary biology.

## More soon

I will soon compile other resources I've made but there not yet made public.

# Past teaching experience as teaching assistant

## University of Michigan

Mentors are all Professors.

### Graduate courses

**2022 ; 2023** _Evolutionary Processes and Macroevolution_ (1 semester each, mentored by Daniel Rabosky)

### Undergraduate courses

**2023** _Introduction to Biology (BIO 171)_ (1 semester, mentored by 
Laura Eidietis)

**2021 ; 2022** _Introduction to Biology Lab (BIO 173)_ (1 semester each, mentored by Laura)

## University of Sao Paulo 

Mentors are all Professors unless otherwise noted.

### Graduate courses

**2020 ; 2018** _VII Southern-Summer School on Mathematical Biology_ (2 weeks each, mentored by Roberto Kraenkel & Paulo Prado)

**2019 ; 2018 ** _Use of R language for ecological data analysis_ (1 semester each, mentored by Alexandre Adalardo)

**2018** _Macroevolution: theory and applications_ (1 semester, mentored by Tiago Quental + Postdocs Gustavo Burin & Laura Alencar)

### Undergraduate courses

**2019 ; 2018 ; 2017** _Supervised training in biology teaching_ (1 semester each, mentored by Daniela Scarpa & Maria Visconti)

**2017** _Virtual ecology: computer simulation models in ecology_ (1 semester, mentored by Paulo Prado, Alexandre Adalardo, & Adriana Martini)

**2017** _Ecology of communities and ecosystems_ (1 semester, mentored by Paulo Guimaraes & Tiago Quental)

**2016** _Biodiversity Conservation_ (1 semester, mentored by Jean Paul Metzger & Vania Pivello)

**2014** _Evolution_ (1 semester, mentored by Diogo Meyer & Gabriel Marroig)

# Past teaching experience as workshop provider

**2024**  Comparative Biology and Functional Morphology in the 21st Century _Gans Foundation Student Workshop for the Society for the Study of Amphibians and Reptiles Meeting_ (Ann Arbor MI USA, 3-day workshop)

**2024**  Seeing Through Trees – Introduction to Phylogenetic Comparative Methods in R _Institute for Global Change Biology stats sessions_ (Ann Arbor MI USA, 2hr workshop)
